# application-alpha.yaml
server:
  shutdown: graceful
logging:
  level:
    root: warn
    com.rest.api: info
  path: /home/wnstn/springapi/log/api.log
  file:
    max-history: 7
spring:
  config:
    activate:
      on-profile: alphaprofile
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wnstn
    password: abcd1234
    url: jdbc:mysql://localhost:36091/springapi?useUnicode=true&autoReconnect=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: 'true'
    generate-ddl: false
    hibernate:
      ddl-auto: none
      format_sql: true
  url:
    base: 127.0.0.1
  lifecycle:
    timeout-per-shutdown-phase: "30s"