# application.yaml
spring:
  profiles:
    active: local
    include:
      - key
  freemarker:
    suffix: .ftl
  application:
    name: api
  messages:
    basename: i18n/exception
    encoding: UTF-8

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true